### ISSUE TITLE
v1.0.9-beta [BUG]: Not working on windows 10

### ISSUE THREAD

**Issue by theSysFish** [KernelWanderers/OCSysInfo#29]
**Describe the bug**
Open and close on windows 10 (clicking on it)
or show error messages when using Cmd

**To Reproduce**
Click to open or by Cmd

**Expected behavior**
Open menu with options

**Platform (please complete the following information):**
 - OS: Windows 10

**Comment by kernel-dev** [comment]
I'm aware of the issue, however this was only an issue with the released binaries. It's been fixed now and should be ok. Feel free to let us know if there are any more issues at hand!
