### ISSUE TITLE
[BUG]: Follow up to 'Module not found (in discussions)

### ISSUE THREAD

**Issue by JGStuff** [KernelWanderers/OCSysInfo#38]
**Describe the bug**
"error opening libpython3.10.dylib"

**To Reproduce**
Simply running MacOS app with Python 3.12

**Expected behavior**
Run without errors :)

**Screenshots**
![Screen Shot 2023-10-21 at 10 58 17 AM](https://github.com/KernelWanderers/OCSysInfo/assets/147350098/9523d082-10c1-4fd6-8ab0-33cce40ba38d)

**Platform (please complete the following information):**
 - OS: [macOS]
 - Version Catalina 10.15.7

**Additional context**

**Comment by Mahas1** [comment]
Should be fixed in #35 
Related issue: #34
